### PR TITLE
Fix alignment for SAMD

### PR DESCRIPTION
**Pull request by gdsports**

### CODE REVIEW

**Comment by NicoHood** [comment]
Did you make sure this still works on avr?

**Comment by NicoHood** [comment]
Can you please also adapt the changes to the other files? They all require this patch it seems
https://github.com/NicoHood/HID/issues/194#issuecomment-667607045

**Comment by gdsports** [comment]
OK, I will fix for other devices and check to make sure it works on AVR. My plan is to add #define ATTRIBUTE_PACKED to HID-Settings.h. For AVR arch, the #define will do nothing so no change for AVR. For SAMD, it wll expand to force 1 byte alignment. Not sure if this is need for SAM (Due). I will check this also.

**Comment by gdsports** [comment]
ATTRIBUTE_PACKED is defined in HID-Settings. For AVR, it does nothing. For SAMD and SAM, alignment is set to prevent the insertion of pad bytes.

The following examples tested on Linux Ubuntu 18.04 using an Arduino Zero (SAMD21). Not sure how to test raw HID and alternate keyboard. Examples also tested on an Arduino Leonardo.

- consumer
- gamepad
- absolute mouse
- improved mouse
- boot keyboard
- improved keyboard
- keyboard led
- nkrokeyboard

**Comment by NicoHood** [comment]
Thanks!

**Pull request merged**
