### PR TITLE
Allow sketches to change the keyboard language layout config without editing source files in the library itself

### PR DESCRIPTION
**Pull request by blahlicus**
As per #175, NicoHood/HID currently requires the user to change the flags in `HID-Settings.h` to switch from US to German keyboard layout and etc.

This is really bad because it requires the user to edit source files in the HID-Project library.

This PR allows sketches to set flags to define which layout it would like to use without messing with source files in the library, below is an example using the German layout:

```
#define HID_CUSTOM_LAYOUT // set this flag to indicate that a custom layout is selected
// if the above flag is not defined, then the default US layout is used instead

#define LAYOUT_GERMAN // set this flag after the above flag to indicate the custom input method is German
// for more layouts, see /src/KeyboardLayouts/ImprovedKeylayouts.h

// you must set the above flags before including HID-Project
#include "HID-Project.h"


void setup() {
  BootKeyboard.begin();
  delay(300);
  BootKeyboard.write(KEY_7|MOD_LEFT_SHIFT); // this outputs the / symbol as per the german input method
}


void loop() {

}
```

To use a non-US English layout, the user only has to `#define HID_CUSTOM_LAYOUT` followed by `#define LAYOUT_[Your layout here]` before `#including` the `HID-Project.h` file.

if `HID_CUSTOM_LAYOUT` is undefined, then it defaults to the original US ASCII table, which means this PR is reverse compatible with older sketches.

### CODE REVIEW

**Comment by wladimir-computin** [comment]
How do you compile it? Are you using the Arduino IDE?

**Comment by blahlicus** [comment]
Yeah.

**Comment by NicoHood** [comment]
Oh nice. This works, because I did not use .cpp files, right? The .cpp files do not require the keyboard layout. This should work - I am surprised that it is that easy. Did you test this carefully?

**Comment by blahlicus** [comment]
I tested the above code on both the Pro Micro and an SAMD21 device.

I also tested it in my complicated firmware which depends on this library and it worked fine. Previous version of my complicated firmware which depends on older versions of this library also works with this so it shows reverse-compatibility is working.

Perhaps we could have a second opinion from @wladimir-computin and then decide on the merge?

**Comment by wladimir-computin** [comment]
In my opinion @blahlicus did a great job, no complaints from my side.
@NicoHood, are you ok with merging his commit?

**Comment by bitboy85** [comment]
Not working for me https://github.com/NicoHood/HID/issues/208
Arduino IDE 1.8.11

**Pull request merged**
