### PR TITLE
Different keyboard layouts

### PR DESCRIPTION
**Pull request by RingoM**
Hi Nico,

Since I'm new to github, version control, ... I was looking for a little project to learn the basics (fork, push, pull, commit, ...).

I like the ability to select the keyboard layout of teensyduino, so I decided to try and implement the teensy keyboard layout functionality into your code. I've seen you also had a request for this (issue #22).

I replaced your keyboard class with the one from teensy and edited it to work with your code. Perhaps, you can use it in your own project. If not, it was a good learning experience for me ;-)

kind regards,

Ringo

P.S. Thanks again for your work with the NKRO keyboard.

### CODE REVIEW

**Comment by NicoHood** [comment]
I haven't tested it yet, did you?
This sounds very cool to me. I will have a look at this soon. Thank you!

The NKRO works fine? May I merge it? If I merge your PR I'll also add the keylayout feature to the NKRO keyboard.

Your PR was commited correct. However I wont directly merge it, since it may conflict with my changes on the dev branch.

**Comment by RingoM** [comment]
I have tested it with the French/Belgian layout and I worked fine for me. If things don't work as expected, I think they also don't work correctly on teensy, since the code is virtually the same.

If you decide to merge it or not, is completely up to you, It was a fun and meaningful excercise for me.

NKRO is working for me, I haven't found any issues yet.

**Comment by NicoHood** [comment]
It would also be interesting if the teensy API is smaller in its implementation, for the same example sketch.

I can test german layout the next days.

**Comment by RingoM** [comment]
What exactly do you mean?

OK, let me know if it's working or not.

**Comment by NicoHood** [comment]
Currently working on 1.6.6 compatibility. This library needs to be ported, but should be possible easily. If we inline the whole code a simple include can be enough to change the language.

Feel free to open a new PR against the dev24 branch or i'll work on this some day.

**Comment by NicoHood** [comment]
See this please:
https://github.com/NicoHood/HID/issues/22#issuecomment-136160943

**Comment by NicoHood** [comment]
Thanks for the help! Without you I would not have been able to add this feature! :)

**Comment by RingoM** [comment]
No problem.
You did an incredible job with this HID project. Keep up the good work!

**Pull request closed without merging**
