### PR TITLE
Create 3DMouseAPI.h

### PR DESCRIPTION
**Pull request by Matesaktesak**

### CODE REVIEW

**Comment by Matesaktesak** [comment]
I have just fixed a bunch of beginner mistakes - I will post them tomorrow

**Comment by NicoHood** [comment]
What is a 3D mouse? Can you please put all your changes in a single PR instead of opening multiple PRs?

**Comment by apm963** [comment]
@NicoHood something like this https://www.3dconnexion.com/products/spacemouse.html. Coincidentally I was recently wondering if this type of device was HID compliant. It would be neat to make one of these since they're definitely not cheap.

**Comment by zaphodbe** [comment]
Yes 3DConnexion is indeed a HID device and is supported by spacenavd project on GitHub independently of 3DConnexion themselves.  Just ported and updated that driver to work properly on MacOS.

**Comment by NicoHood** [comment]
I am happy to merge a good quality PR for such a mouse. Maybe anyone of you is willing to have a look at the patches provided?

**Comment by apm963** [comment]
@NicoHood I have created #226 which is a consolidation of the 4 PRs by @Matesaktesak. There was a fifth PR that I ignored because it only modified a commented out line of code and was inconsequential. I didn't rebase and have not yet tested. I'll try to get this tested within a week if I have the opportunity but if anybody else on this thread can test earlier, that would be good.

**Pull request closed without merging**
