### PR TITLE
Allow reducing gamepad buttons to 16 and removing Z-Axis easily

### PR DESCRIPTION
**Pull request by SukkoPera**
This patch does nothing by default, but adds a few configuration options for the above into HID-Settings.h.

### CODE REVIEW

**Comment by NicoHood** [comment]
Why would you need this? Isn't more always better than less?

**Comment by SukkoPera** [comment]
Not really, IMHO. Who needs 32 buttons? Which commercial controller has that many buttons? Implementing a 4-button controller and leaving 28 unused looks poor.

Besides that, a shorter USB report is probably ((very) slightly) quicker to transmit, which yields more CPU time.

**Comment by NicoHood** [comment]
Flight simulator developers are more than happy for every button or axis they have.

The USB time is not really an argument for me.

**Comment by SukkoPera** [comment]
Right, still I don't think that 99% of who is using this library has more than a few buttons. Anyway this PR has no impact on the default behaviour, it just adds a few settings that can be tweaked by advanced users, so flight simulator users will still be happy.

**Comment by SukkoPera** [comment]
Upon testing on Windows 10, let me report that disabling the Z axis (i.e.: commenting out `HID_ENABLE_ZAXIS`) will result in the controller not being recognized.

On the other hand, reducing the buttons to 16 (`HID_ENABLE_32BUTTONS`) has no such impact and the controller still works fine.

If you want, I can remove the former from the PR.

**Comment by NicoHood** [comment]
Honestly I do not think that this change is helpful for at least 1% of the library users. So I am not really into bloating the library with reducing its functionality for no good reason. I'd rather create a whole separate device called 'joystick' for example with even less buttons. I think I even had that before, but in general it made no sense, as you can just use the "better" device.

**Comment by SukkoPera** [comment]
I don't think this would bloat the library, it would rather be unnoticed by most users IMHO, but that's ok, you're the boss :).

**Comment by DRSDavidSoft** [comment]
@NicoHood I prefer to report the buttons that the project _actually_ have, so I'll be really pleased to be able to somehow define how many buttons are connected to the device :)

**Pull request closed without merging**
